### PR TITLE
Rework the input channel to be less tightly coupled

### PR DESCRIPTION
**Pull request by jcorbin**

### CODE REVIEW

**Comment by jcorbin** [comment]
Almost ripped termbox out of view et al, but didn't make it to done. This starts down the road tho.

I can't explain why, but I really dislike the Move/ShiftedMove type puns... I barely like my RelativeMove wrapper a little better...

Went back and forth locally on whether to inject some `shifted func(image.Point) image.Point` transform, but decided I hate the multiplier "value add" less; the downfall of the injection is it forces you to either rebuild the command channel, or indirect the transform, if you need to ever re-define the transform. Where-as you can always decide how to respond to a piece of data (type pun, bool flag, or otherwise) later...

**Comment by kriskowal** [comment]
I don't expect either of these approaches to even resemble the final form.
We will need a state monad for all mode sensitive input, so input will
probably need to be managed off the render goroutine, occasionally
requesting an async draw.

Not attached to any names or approach.

**Comment by jcorbin** [comment]
Right, let's start unpacking all that:

## Reading / Scanning / Recognizing

What I wanted to talk about / sort out on this PR is a step forward for our lower layer "terminal whisperer" (really "terminal *listener*", existing `cops` being the whisperer...)

At this layer I'd like to sort out some sort of a pluggable system that:
- allows us to integrate mouse input
- allows for configurable mappings, e.g. for input some prefer vi, arrow keys, numpad, or heck even an adapted wasd-like thing...
- also need a standard "terminal idioms" mapping, e.g. for things like ^C to interrupt, ^L to force redraw, ^Z to suspend, ^[ to exit/cancel, (and innovations like ^\ to debug dump, ^] to turn on perf tooling...)

But in short, what we're talking about here is a, as you sketched, stream of "letters", "tokens", what we call `command`s. This is essentially the language *on top of which* we later build a parser of any ilk.

For maximum confidence/reliability, many of the commands (e.g. redraw, interrupt, debug) should be handled as boringly as possible (minimal cleverness); this is also the same reason not to conflate or smash together the command reading layer with a stateful parsing layer. In fact the part that reacts to those sorts of commands is probably a thing intermediary between reading and any:

## Parsing (by hook, crook, or monad...)

The most I've experimented towards this aspect has been:
- `internal/view`'s `HandleKey(KeyEvent) error` thing
- `internalprompt`'s `func(KeyEvent) (handled bool, err error)` (-ish, the need for other boolean traps ran a bit rampant)
- but the one that worked most well, and is most monadic, is the `func(prior Prompt) (next Prompt, prompting bool)`; the `Prompt` here is the state, and `prompting` is an interplay with the world simulation, if `true` we're still doing prompt interaction on pause, but once `false` the prompt is "done" and the wold moves on

We do need to square this against rendering at some point, but it's all a fundamentally much higher level, and probably much more domain-specific layer.

## Back on reading

What I hoped to work though in this PR:
- I like your `interface{}` stream; may want to consider some `type Command interface{}`
- I'm dubious on the finality of my `func(rune, io.RuneScanner) error` also:
- in particular I suspect we may just specialize to pass `*bufio.Reader` but didn't want to start there...

**Comment by kriskowal** [comment]
Supposing that we enter a mode for accepting a string, e.g., "Elbereth". How do we avoid confusing the L for a direction command? It’s possible that we extend buffered reader with methods to read commands, so the mode governs whether to consume runes or commands.

**Comment by jcorbin** [comment]
Good point... maybe I was too initially infatuated with the `interface{}` approach; once I get through my "dark night of the display" in #31, I'll rethink its input system along these principles:
- provide a concrete stream like `struct { Key Rune; Point }`
- exotic things like arrow keys, mice, and other keycodes represented by special codepoints (probably some PUA range)
- all semantics, like modality and mappings left up to a higher layer

Alternately to the "union struct", we could go for a handler interface dual, such as:
```
type InputHandler interface {
  HandleKey(rune)
  HandleMouseDown(int, Point)
  // etc...
}
```

**Comment by jcorbin** [comment]
- [anansi.Input](https://godoc.org/github.com/jcorbin/anansi#Input)
- anansi [xplatform.Events](https://godoc.org/github.com/jcorbin/anansi/x/platform#Events)

**Pull request closed without merging**
