### PR TITLE
Breakup cops cursor logic; simplify render

### PR DESCRIPTION
**Pull request by jcorbin**
More internal surface area, used by render.

### CODE REVIEW

**Comment by jcorbin** [comment]
Small perf win, if any:
```                                                      
name                old time/op    new time/op    delta                 
_displayDemo/4-4      4.57µs ± 0%    4.16µs ± 0%   ~     (p=1.000 n=1+1)         
_displayDemo/8-4      16.2µs ± 0%    15.0µs ± 0%   ~     (p=1.000 n=1+1)   
_displayDemo/16-4     61.2µs ± 0%    58.0µs ± 0%   ~     (p=1.000 n=1+1)
_displayDemo/32-4      241µs ± 0%     230µs ± 0%   ~     (p=1.000 n=1+1)
_displayDemo/64-4      957µs ± 0%     920µs ± 0%   ~     (p=1.000 n=1+1)                                      
_displayDemo/128-4    3.85ms ± 0%    3.71ms ± 0%   ~     (p=1.000 n=1+1)                                        
_displayDemo/256-4    15.7ms ± 0%    15.1ms ± 0%   ~     (p=1.000 n=1+1)            
```
But worth more in other ilities like read- and flex-.

**Comment by jcorbin** [comment]
Yeah btw that strict 24 bit model? That's going to be a bigger perf boost
than almost anything else left; already peeked down that corridor, and the
map/if branch are quite noticeable in profiles; also fwiw, I wasn't able to
beat the map access with anything more ruthless (like a 256-case switch...)

Also there's a small bug in this PR that I'll push fix for once I'm not
roaming.

**Comment by jcorbin** [comment]
Model fix in #16.

**Comment by kriskowal** [comment]
Let’s just go for strict 24 by default. The fallbacks are optimizing for wire, at the expense of accurate color. The terminal is not guaranteed to respect the 256 color palette I’ve embedded.

**Comment by jcorbin** [comment]
You may be excited to know that this PR fixes a visual glitch in the braillewave demo, and I'm not really sure why...

**Comment by kriskowal** [comment]
@jcorbin Excited indeed! I couldn’t figure that out!

**Pull request merged**
